// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiCoreApp.DataAccessLayer;

#nullable disable

namespace MultiCoreApp.DataAccessLayer.Migrations
{
    [DbContext(typeof(MultiDbContext))]
    [Migration("20220419074613_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MultiCoreApp.Core.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tblCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d83b745-14ee-4bbf-9919-1de19f80b102"),
                            IsDeleted = false,
                            Name = "Kalemler"
                        },
                        new
                        {
                            Id = new Guid("1a88a757-f840-4f11-b512-e1ee81ebb285"),
                            IsDeleted = false,
                            Name = "Defterler"
                        });
                });

            modelBuilder.Entity("MultiCoreApp.Core.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tblCustomer", (string)null);
                });

            modelBuilder.Entity("MultiCoreApp.Core.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("tblProducts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("65c589ab-eda3-4d67-beef-f650dcf46b4d"),
                            CategoryId = new Guid("6d83b745-14ee-4bbf-9919-1de19f80b102"),
                            IsDeleted = false,
                            Name = "Dolma Kalem",
                            Price = 12.53m,
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("1485daaa-28d8-412b-a0f5-140f456e21f1"),
                            CategoryId = new Guid("6d83b745-14ee-4bbf-9919-1de19f80b102"),
                            IsDeleted = false,
                            Name = "Tükenmez Kalem",
                            Price = 122.13m,
                            Stock = 12
                        },
                        new
                        {
                            Id = new Guid("760f8b1e-69be-4938-a7ec-57baeee21d98"),
                            CategoryId = new Guid("6d83b745-14ee-4bbf-9919-1de19f80b102"),
                            IsDeleted = false,
                            Name = "Kurşun Kalem",
                            Price = 1.49m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = new Guid("c432905d-9144-4b11-8f68-a9bb81900927"),
                            CategoryId = new Guid("1a88a757-f840-4f11-b512-e1ee81ebb285"),
                            IsDeleted = false,
                            Name = "Çizgili Defter",
                            Price = 12.32m,
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("1821f27c-cc85-4638-b58c-80b0a0a8ed0f"),
                            CategoryId = new Guid("1a88a757-f840-4f11-b512-e1ee81ebb285"),
                            IsDeleted = false,
                            Name = "Kareli Defter",
                            Price = 15.21m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = new Guid("0ae27214-1a42-4aad-8fd9-b23a1a291c5e"),
                            CategoryId = new Guid("1a88a757-f840-4f11-b512-e1ee81ebb285"),
                            IsDeleted = false,
                            Name = "Dumdüz Defter",
                            Price = 10.79m,
                            Stock = 1000
                        });
                });

            modelBuilder.Entity("MultiCoreApp.Core.Models.Product", b =>
                {
                    b.HasOne("MultiCoreApp.Core.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MultiCoreApp.Core.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
